resolver 127.0.0.11 valid=5s ipv6=off;

upstream tempconverter_app {
    zone tempconverter_app 64k;
    least_conn;
    server app:5000 resolve;
}

server {
    listen 80 default_server;
    server_name _;

    location / {
        proxy_pass http://tempconverter_app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
        proxy_read_timeout 10s;
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
}
